# Generated by Django 4.2.1 on 2023-05-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='phone_images/', verbose_name='Изображение')),
                ('release_date', models.DateField(verbose_name='Дата изготовления')),
                ('lte_exists', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
